/*
  ___   _   _   ___   _   _ _____ ___   _   __
 / _ \ | \ | | / _ \ | \ | |_   _/ _ \ | | / /
/ /_\ \|  \| |/ /_\ \|  \| | | |/ /_\ \| |/ /
|  _  || . ` ||  _  || . ` | | ||  _  ||    \
| | | || |\  || | | || |\  | | || | | || |\  \
\_| |_/\_| \_/\_| |_/\_| \_/ \_/\_| |_/\_| \_/

Project Snowgazer Snowgazer.h library header
Initial file automatically generated by PROGENY on 09/21/24 16:00:04

 This file contains all header definitions used by test executables
*/

#ifndef Snowgazer_H
#define Snowgazer_H

#endif //Snowgazer_H
